(()=>{'use strict';const ticket=document.querySelector('#punch-ticket'),holes=document.querySelector('#ticket-holes'),status=document.querySelector('#punch-status'),hint=document.querySelector('#ticket-hint'),reset=document.querySelector('#reset-ticket');let count=0,routeIndex=0;const rims=document.querySelector('#punch-rims');
const routes=[['東京都区内','名古屋市内','TOKYO','NAGOYA','東海道'],['札幌','旭川','SAPPORO','ASAHIKAWA','函館'],['仙台','盛岡','SENDAI','MORIOKA','東北'],['京都','大阪','KYOTO','OSAKA','東海道'],['岡山','高松','OKAYAMA','TAKAMATSU','宇野・本四備讃・予讃'],['博多','熊本','HAKATA','KUMAMOTO','鹿児島']];
function changeRoute(){routeIndex=(routeIndex+1+Math.floor(Math.random()*(routes.length-1)))%routes.length;const r=routes[routeIndex];['ticket-from','ticket-to','ticket-from-en','ticket-to-en','ticket-via'].forEach((id,i)=>document.getElementById(id).textContent=(i===4?'経由：':'')+r[i]);ticket.querySelector('svg').setAttribute('aria-label',`JR 紙质乘车券风格纪念票，${r[0]}至${r[1]}`);}

ticket.addEventListener('click',event=>{if(count>=12){hint.textContent='这张票已经收集了好多回忆，换一张继续吧。';return;}const svg=ticket.querySelector('svg');let x=35+count*28,y=223;if(event.detail){const point=new DOMPoint(event.clientX,event.clientY).matrixTransform(svg.getScreenCTM().inverse());x=Math.min(424,Math.max(16,point.x));y=Math.min(242,Math.max(16,point.y));}const hole=document.createElementNS('http://www.w3.org/2000/svg','circle');hole.setAttribute('cx',x);hole.setAttribute('cy',y);hole.setAttribute('r',13);hole.setAttribute('fill','black');holes.append(hole);const rim=hole.cloneNode();rim.setAttribute('fill','none');rims.append(rim);count++;status.textContent=`咔哒，已为车票打下第 ${count} 个孔。`;hint.textContent='咔哒。下一站，去留下你的足迹。';reset.hidden=false;});
reset.addEventListener('click',()=>{holes.replaceChildren();rims.replaceChildren();changeRoute();count=0;reset.hidden=true;hint.textContent='移到车票上，咔哒一下，为旅程打个孔。';status.textContent='已换一张新车票。';ticket.focus();});
const station=document.querySelector('#crossing-station'),stationName=document.querySelector('#crossing-name'),stations=['新宿','东京','大阪','札幌','长野','名古屋'];const roman=['SHINJUKU','TOKYO','OSAKA','SAPPORO','NAGANO','NAGOYA'];let stationIndex=1;station.addEventListener('click',()=>{stationIndex=(stationIndex+1)%stations.length;stationName.textContent=stations[stationIndex];document.querySelector('#station-roman').textContent=roman[stationIndex];station.setAttribute('aria-label',`当前站名：${stations[stationIndex]}，点击切换`);});
const medal=document.querySelector('#sample-medal');RailHonors.applyTheme(RailHonors.tiers[4],medal);medal.innerHTML=RailHonors.medal;
})();
