(()=>{'use strict';
const assets={"overview":{"file":"overview-v3-1ce3f7ecb8426ddd.bin","sha256":"1ce3f7ecb8426ddd4fb97ade1ebfb6443a9e5b3b929a9fc30b2a707ff1c58464","bytes":442139},"core":{"file":"core-v3-37fcbdbc8d618211.bin","sha256":"37fcbdbc8d6182114a739f5faf7c20c723eae46b9cd05e2af4cd88908fc53b9d","bytes":1363048,"format":"rail-core-v3"}},q=s=>document.querySelector(s),panel=q('#data-loading'),message=q('#data-load-message'),retry=q('#data-load-retry'),main=q('main');let busy=false,starting=false,core,D;const jobs=new Map(),loaded=new Set(),detailsLoaded=new Set(),detailGroup=new Map();
function decodeCore(bytes){const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),length=view.getUint32(0,true);if(length>bytes.length-4)throw Error('header');const core=JSON.parse(new TextDecoder().decode(bytes.subarray(4,4+length)));if(core.schema!==3)throw Error('schema');let offset=4+length;function uint(){let n=0,f=1,b,count=0;do{if(offset>=bytes.length||++count>8)throw Error('integer');b=bytes[offset++];n+=(b%128)*f;f*=128}while(b>=128);if(!Number.isSafeInteger(n))throw Error('integer range');return n}function signed(){const n=uint();return n%2?-(n+1)/2:n/2}core.edgeLengthsMm=Array.from({length:core.edgeCount},uint);const ids=core.sections.map(s=>s[0]);core.sections=core.sections.map(([id,chunk])=>{const runs=[],count=uint();let end=0;for(let i=0;i<count;i++){const start=end+signed(),length=uint();if(start<0||start+length>core.edgeCount)throw Error('edge range');runs.push([start,length]);end=start+length}return [id,runs,chunk]});core.lines=core.lines.map(([id,group])=>{const count=uint(),sectionIds=[];let prev=0;for(let i=0;i<count;i++){prev+=signed();if(!ids[prev])throw Error('section index');sectionIds.push(ids[prev])}detailGroup.set(id,group);return {id,sectionIds,stations:[],routingStations:[]}});if(offset!==bytes.length)throw Error('trailing bytes');return core}
async function ensureDetails(l){if(detailsLoaded.has(l.id))return;const group=await request(core.details[detailGroup.get(l.id)]);const info=group.find(x=>x.id===l.id);if(!info)throw Error('missing stations');Object.assign(l,info);detailsLoaded.add(l.id)}
function script(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>{s.remove();reject(Error('script '+src))};document.body.append(s)})}
async function request(a){if(jobs.has(a.file))return jobs.get(a.file);const job=(async()=>{let cache;try{cache=await caches.open('rail-atlas-assets-v2')}catch{}let response;try{response=await cache?.match(a.file)}catch{}const fromCache=!!response;const controller=new AbortController();let timer;const touch=()=>{clearTimeout(timer);timer=setTimeout(()=>controller.abort(),45000)};touch();try{if(!response){response=await fetch(a.file,{signal:controller.signal});if(!response.ok)throw Error('http '+response.status)}const reader=response.body.getReader(),parts=[];let n=0;for(;;){const {done,value}=await reader.read();if(done)break;touch();n+=value.length;parts.push(value)}if(n!==a.bytes)throw Error('size');const bytes=new Uint8Array(n);let offset=0;for(const p of parts){bytes.set(p,offset);offset+=p.length}if(crypto.subtle){const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),n=>n.toString(16).padStart(2,'0')).join('');if(hash!==a.sha256)throw Error('integrity')}const unpacked=new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer());const json=a.format==='rail-core-v3'?decodeCore(unpacked):JSON.parse(new TextDecoder().decode(unpacked));if(!fromCache)try{await cache?.put(a.file,new Response(bytes))}catch{}return json}catch(e){try{await cache?.delete(a.file)}catch{}throw e}finally{clearTimeout(timer)}})();jobs.set(a.file,job);try{return await job}catch(e){jobs.delete(a.file);throw e}}
async function geometry(ids){const missing=[...new Set(ids)].filter(i=>!loaded.has(i));let cursor=0;await Promise.all(Array.from({length:Math.min(4,missing.length)},async()=>{while(cursor<missing.length){const i=missing[cursor++],packed=await request(core.chunks[i]);for(const [id,encoding,coords,e,v] of packed.sections){let prev=[0,0];const c=encoding===1?coords.map(pair=>pair.map((d,a)=>(prev[a]+=d)/1e8)):coords;Object.assign(D.sections[id],{c,e,v:v===null?[...e]:v})}loaded.add(i)}}))}
function missingFootprint(edges){const ids=new Set();for(const s of Object.values(D.sections))if(!loaded.has(s.chunk)&&s.e.some(e=>edges.has(e)))ids.add(s.chunk);return [...ids]}
function preview(o){const svg=d3.select('#map'),w=q('#mapwrap').clientWidth,h=q('#mapwrap').clientHeight;svg.attr('viewBox',`0 0 ${w} ${h}`);const projection=d3.geoMercator().fitExtent([[25,45],[w-25,h-45]],{type:'MultiPoint',coordinates:[[123,24],[146,45.8]]}),path=d3.geoPath(projection);svg.selectAll('*').remove();svg.append('g').selectAll('path').data(o.land.features).join('path').attr('class','land').attr('d',path);svg.append('g').selectAll('path').data(o.lines).join('path').attr('class',l=>'route'+(l.kind==='1'?' fast':'')).attr('d',l=>path(l.geometry));panel.classList.add('compact');document.dispatchEvent(new Event('rail-overview-ready'))}
async function start(){if(busy)return;if(starting){location.reload();return}busy=true;retry.hidden=true;main.inert=true;q('#toggle-sidebar').disabled=true;q('#sidebar').hidden=true;message.textContent='正在展开全国铁路…';try{if(location.protocol==='file:'||typeof DecompressionStream==='undefined'){await script('data.js')}else{const o=await request(assets.overview);preview(o);message.textContent='地图已展开，正在准备足迹统计…';core=await request(assets.core);D={...o,edgeLengthsMm:core.edgeLengthsMm,totalMm:core.totalMm,titles:core.titles,sections:{}};const byId=new Map(D.lines.map(l=>[l.id,l]));for(const l of core.lines)Object.assign(byId.get(l.id),l);for(const [id,runs,chunk] of core.sections){D.sections[id]={id,e:runs.flatMap(([s,n])=>Array.from({length:n},(_,i)=>s+i)),v:[],c:[]};Object.defineProperty(D.sections[id],'chunk',{value:chunk})}window.RAIL_DATA=D;window.RailAssets={hasLine:l=>detailsLoaded.has(l.id)&&l.sectionIds.every(id=>loaded.has(D.sections[id].chunk)),ensureLine:l=>Promise.all([ensureDetails(l),geometry(l.sectionIds.map(id=>D.sections[id].chunk))]),needsFootprint:edges=>missingFootprint(edges).length>0,ensureFootprint:edges=>geometry(missingFootprint(edges))};}
starting=true;d3.select('#map').selectAll('*').remove();await script('app.js?v=f0cac3f92e48');if(!window.RailAtlas)throw Error('initialization');await script('export.js?v=70c1b2fbe784');await script('polish.js?v=47d959ef053a');panel.hidden=true;main.inert=false;q('#toggle-sidebar').disabled=false;document.dispatchEvent(new Event('rail-data-ready'))}catch(e){console.error('Railway load failed',e);message.textContent='加载未完成，请检查网络后重试。';retry.hidden=false}finally{busy=false}}
retry.onclick=start;start();
})();
