(()=>{'use strict';const q=s=>document.querySelector(s),dialog=q('#export-dialog');let crop=null,cropCamera=null,blob=null,url=null,layer=null,toolbar=null,busy=false;
function invalidate(){blob=null;q('#download-export').disabled=true;q('#export-preview').hidden=true;if(url){URL.revokeObjectURL(url);url=null}q('#export-status').textContent=''}
q('#open-export').onclick=()=>{RailAtlas.prepareExport();invalidate();dialog.showModal()};q('#close-export').onclick=()=>dialog.close();q('#export-range').onchange=()=>{invalidate();q('#choose-crop').hidden=q('#export-range').value!=='custom';q('#crop-summary').textContent=q('#export-range').value==='custom'?(crop?'已选择范围，可重新框选。':'先在地图上框选要留下的旅程。'):''};q('#include-honors').onchange=invalidate;document.addEventListener('footprint-imported',invalidate);
function endCrop(){layer?.remove();toolbar?.remove();layer=toolbar=null;dialog.showModal()}
q('#choose-crop').onclick=()=>{dialog.close();RailAtlas.prepareExport();const wrap=q('#mapwrap');layer=document.createElement('div');layer.className='crop-layer';const rect=document.createElement('div');rect.className='crop-rect';rect.hidden=true;layer.append(rect);toolbar=document.createElement('div');toolbar.className='crop-toolbar';const label=document.createElement('span');label.textContent='拖动框选截图范围';const confirm=document.createElement('button');confirm.textContent='使用范围';confirm.disabled=true;const cancel=document.createElement('button');cancel.textContent='取消';toolbar.append(label,confirm,cancel);wrap.append(layer,toolbar);let start=null,next=null,camera=RailAtlas.getExportState();
const pos=e=>{const b=layer.getBoundingClientRect();return [Math.max(0,Math.min(b.width,e.clientX-b.left)),Math.max(0,Math.min(b.height,e.clientY-b.top))]};
layer.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();start=pos(e);next=null;confirm.disabled=true;rect.hidden=false;rect.style.cssText=`left:${start[0]}px;top:${start[1]}px;width:0;height:0`;layer.setPointerCapture(e.pointerId)};
layer.onpointermove=e=>{if(!start)return;const p=pos(e);next={x:Math.min(start[0],p[0]),y:Math.min(start[1],p[1]),width:Math.abs(start[0]-p[0]),height:Math.abs(start[1]-p[1])};Object.assign(rect.style,{left:next.x+'px',top:next.y+'px',width:next.width+'px',height:next.height+'px'})};
layer.onpointerup=()=>{start=null;confirm.disabled=!next||next.width<40||next.height<40};layer.onpointercancel=()=>{start=null;next=null;confirm.disabled=true;rect.hidden=true};confirm.onclick=()=>{crop=next;cropCamera=camera;invalidate();q('#crop-summary').textContent='已选择范围';endCrop()};cancel.onclick=endCrop;confirm.focus()};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&layer){e.preventDefault();endCrop()}});window.addEventListener('resize',()=>{if(layer){endCrop();q('#crop-summary').textContent='窗口尺寸已改变，请重新框选。'}});
function roundRect(c,x,y,w,h,r=15){c.beginPath();c.roundRect(x,y,w,h,r)}
async function medalImage(tier){const colors=tier.id==='complete'?['#938bad','#d5f7f0','#fff','#e8c9ee','#d5e6ff','#ba97b8']:[tier.shade,tier.light,'#fff',tier.light,tier.shade,tier.light];const offsets=tier.id==='complete'?[0,25,42,56,78,100]:[0,30,43,48,70,100];const icon=RailHonors.medal.replace('<svg ','<svg x="16" y="17" width="30" height="30" ').replaceAll('currentColor',tier.dark);const source=`<svg xmlns="http://www.w3.org/2000/svg" width="62" height="76" viewBox="0 0 62 76"><defs><linearGradient id="metal" x2="1" y2="1">${colors.map((v,i)=>`<stop offset="${offsets[i]}%" stop-color="${v}"/>`).join('')}</linearGradient><pattern id="grain" width="3" height="3" patternUnits="userSpaceOnUse" patternTransform="rotate(22)"><path d="M0 0v3" stroke="#fff" stroke-opacity=".13"/><path d="M1 0v3" stroke="#000" stroke-opacity=".05"/></pattern></defs><rect x="7" y="7" width="48" height="57" rx="17" fill="#000" opacity=".13"/><path d="M23 3h16q17 0 17 17v17q0 23-23 23h-4Q6 60 6 37V20Q6 3 23 3Z" fill="url(#metal)" stroke="${tier.light}" stroke-width="2"/><path d="M23 7h16q13 0 13 13v17q0 19-19 19h-4Q10 56 10 37V20Q10 7 23 7Z" fill="url(#grain)" stroke="#fff" stroke-opacity=".4" stroke-width="2"/><path d="M23 9h16q11 0 11 11v17q0 17-17 17h-4Q12 54 12 37V20Q12 9 23 9Z" fill="none" stroke="#000" stroke-opacity=".18"/>${icon}</svg>`;const img=new Image();img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(source);await img.decode();return img}
async function render(){if(busy)return;const mode=q('#export-range').value,include=q('#include-honors').checked;if(mode==='custom'&&!crop){q('#export-status').textContent='请先在地图上框选范围。';return}busy=true;for(const id of ['#export-range','#include-honors','#choose-crop'])q(id).disabled=true;invalidate();q('#render-export').disabled=true;q('#export-status').textContent='正在生成…';try{await document.fonts.ready;await new Promise(r=>requestAnimationFrame(r));const current=RailAtlas.getExportState(),state=mode==='custom'?cropCamera:current,range=mode==='custom'?crop:{x:0,y:0,width:state.width,height:state.height};const W=1800,pad=76,mapW=W-2*pad,mapH=mode==='national'?1640:Math.max(320,Math.min(2300,mapW*range.height/range.width)),mapY=226;const extra=current.honors.extraHonors;const footerH=include?280+Math.ceil(extra.length/3)*60:100,H=mapY+mapH+footerH+pad;const canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const c=canvas.getContext('2d');c.fillStyle='#f5f1e8';c.fillRect(0,0,W,H);c.strokeStyle='#dbd4c3';c.lineWidth=2;c.strokeRect(30,30,W-60,H-60);c.fillStyle='#7e8874';c.font='500 19px system-ui';c.fillText('J A P A N   R A I L   A T L A S',pad,92);c.fillStyle='#354339';c.font='800 62px system-ui';c.fillText('我的铁路足迹',pad,174);c.font='400 23px system-ui';c.fillStyle='#8c927e';c.textAlign='right';c.fillText(mode==='national'?'JAPAN / 全日本':mode==='custom'?'MY JOURNEY / 自选范围':'MY JOURNEY / 当前视野',W-pad,164);c.textAlign='left';
let proj;if(mode==='national')proj=d3.geoMercator().fitExtent([[pad+24,mapY+25],[W-pad-24,mapY+mapH-25]],{type:'MultiPoint',coordinates:[[123,24],[146,45.8]]});else{const scale=Math.min(mapW/range.width,mapH/range.height),ox=pad+(mapW-range.width*scale)/2,oy=mapY+(mapH-range.height*scale)/2;proj=d3.geoMercator().scale(state.projectionScale*state.transform.k*scale).translate([(state.projectionTranslate[0]*state.transform.k+state.transform.x-range.x)*scale+ox,(state.projectionTranslate[1]*state.transform.k+state.transform.y-range.y)*scale+oy])}
c.save();c.beginPath();c.rect(pad,mapY,mapW,mapH);c.clip();const path=d3.geoPath(proj,c);for(const f of RAIL_DATA.land.features){c.beginPath();path(f);c.fillStyle='#fcfaf3';c.fill();c.strokeStyle='#d9d8cb';c.lineWidth=1.2;c.stroke()}for(const l of RAIL_DATA.lines){c.beginPath();path(l.geometry);c.strokeStyle=l.kind==='1'?'#548399':'#b9bcaf';c.lineWidth=l.kind==='1'?2.8:1.5;c.stroke();if(l.kind==='1'){c.setLineDash([6,5]);c.lineWidth=.8;c.strokeStyle='#fffdf6';c.stroke();c.setLineDash([])}}
const used=new Set(current.edgeIds),seen=new Set();c.strokeStyle='#bb9652';c.lineWidth=9;c.lineJoin='round';c.lineCap='round';c.beginPath();for(const s of Object.values(RAIL_DATA.sections))for(let i=0;i<s.v.length;i++){const e=s.v[i];if(e===null||!used.has(e)||seen.has(e))continue;seen.add(e);const a=proj(s.c[i]),b=proj(s.c[i+1]);c.moveTo(...a);c.lineTo(...b)}c.stroke();const occupied=[];c.font='500 21px system-ui';for(const [name,lon,lat] of RAIL_CITIES){const [x,y]=proj([lon,lat]),tw=c.measureText(name).width;if(x<pad+10||x+tw+14>W-pad||y<mapY+25||y>mapY+mapH-20||occupied.some(p=>Math.abs(p[0]-x)<tw+20&&Math.abs(p[1]-y)<30))continue;occupied.push([x,y]);c.fillStyle='#84907d';c.beginPath();c.arc(x,y,3,0,Math.PI*2);c.fill();c.strokeStyle='#fcfaf3';c.lineWidth=5;c.strokeText(name,x+9,y+7);c.fillStyle='#73826d';c.fillText(name,x+9,y+7)}c.restore();
let y=mapY+mapH+42;c.strokeStyle='#d8d2c1';c.lineWidth=1;c.beginPath();c.moveTo(pad,y);c.lineTo(W-pad,y);c.stroke();if(include){y+=68;c.fillStyle='#77836e';c.font='400 23px system-ui';c.fillText('全国覆盖率',pad,y);c.fillStyle='#354339';c.font='800 72px system-ui';c.fillText((current.footprint.ratio*100).toFixed(2)+'%',pad,y+84);c.font='400 22px system-ui';c.fillStyle='#838c77';c.fillText((current.footprint.mm/1e6).toFixed(1)+' km 的旅行记忆',pad,y+123);const tier=RailHonors.tiers.find(t=>t.id===current.footprint.title.id)||RailHonors.tiers[0],x=W-730,gy=y+2,medal=await medalImage(tier);c.drawImage(medal,x,gy,90,108);c.textAlign='left';c.font='750 35px system-ui';c.fillStyle='#40503e';c.fillText(current.footprint.title.name,x+108,gy+59);y+=173;extra.forEach((h,i)=>{const bx=pad+(i%3)*550,by=y+Math.floor(i/3)*60;roundRect(c,bx,by,510,44,8);c.fillStyle='#ece5d2';c.fill();c.fillStyle='#806e44';c.font='600 22px system-ui';c.fillText(h.name,bx+18,by+30)})}
c.fillStyle='#949782';c.font='400 16px system-ui';c.fillText('Railway: MLIT N02-25 · CC BY 4.0 (modified)  |  Land: Natural Earth · Public Domain',pad,H-46);blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('无法生成图片')),'image/png'));url=URL.createObjectURL(blob);q('#export-preview').src=url;q('#export-preview').hidden=false;q('#download-export').disabled=false;q('#export-status').textContent=W+' × '+H+' · PNG';}catch(e){q('#export-status').textContent='生成失败，请重试。';console.error(e)}finally{busy=false;for(const id of ['#export-range','#include-honors','#choose-crop'])q(id).disabled=false;q('#render-export').disabled=false}}
q('#render-export').onclick=render;q('#download-export').onclick=()=>{if(!blob||!url)return;const a=document.createElement('a');a.href=url;a.download='我的铁路足迹-'+q('#export-range').value+'.png';a.click()};
})();

