(()=>{'use strict';const main=document.querySelector('main'),pages=[...main.querySelectorAll(':scope > .page-panel')],dots=[...document.querySelectorAll('.page-dots button')];let index=0,lockedUntil=0,touchY=null,wheelTimer=null,wheelSum=0;const motion=matchMedia('(prefers-reduced-motion: reduce)');const region=['kanto','kansai','kyushu'][Math.floor(Math.random()*3)];document.querySelector('.regional-network').src=`cover-network-${region}.svg`;
const fitPages=()=>document.querySelectorAll('.page-content').forEach(c=>{let f=c.querySelector('.page-fit');if(!f){f=document.createElement('div');f.className='page-fit';while(c.firstChild)f.append(c.firstChild);c.append(f)}f.style.transform='none';const style=getComputedStyle(c),h=c.clientHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom);f.style.transform=`scale(${Math.min(1,h/f.scrollHeight)})`;});
const dialog=document.createElement('dialog');dialog.className='info-dialog';dialog.innerHTML='<button aria-label="关闭">×</button><div></div>';document.body.append(dialog);dialog.querySelector('button').onclick=()=>dialog.close();document.querySelectorAll('.secret-guide,.credits').forEach(d=>{d.querySelector('summary').onclick=e=>{e.preventDefault();dialog.querySelector('div').replaceChildren(...[...d.children].filter(el=>el.tagName!=='SUMMARY').map(el=>el.cloneNode(true)));dialog.showModal()}});requestAnimationFrame(fitPages);document.fonts.ready.then(fitPages);window.addEventListener('resize',fitPages);

function fitRibbon(){const svg=document.querySelector('.plan-b-path');if(!svg)return;const cover=document.querySelector('.cover'),box=cover.getBoundingClientRect(),ticket=document.querySelector('#punch-ticket').getBoundingClientRect(),w=box.width,h=box.height,cx=(ticket.left+ticket.right)/2-box.left,cy=(ticket.top+ticket.bottom)/2-box.top,top=h*.13,bottom=h*.89,k=Math.min(.68,(w*.94-cx)/Math.max(1,bottom-cy)),sx=cx-k*(cy-top),ex=cx+k*(bottom-cy);svg.setAttribute('viewBox',`0 0 ${w} ${h}`);const d=`M-20 ${top}H${sx-15}Q${sx} ${top} ${sx+10*k} ${top+10}L${ex-10*k} ${bottom-10}Q${ex} ${bottom} ${ex+15} ${bottom}H${w+20}`;svg.querySelectorAll('path').forEach(p=>p.setAttribute('d',d));const path=svg.querySelector('path'),length=path.getTotalLength();svg.querySelectorAll('circle').forEach((c,i)=>{const pt=path.getPointAtLength(length*[.14,.34,.52,.82,.96][i]);c.setAttribute('cx',pt.x);c.setAttribute('cy',pt.y);c.setAttribute('r',w<700?6:10)})}
requestAnimationFrame(fitRibbon);document.fonts.ready.then(fitRibbon);window.addEventListener('resize',fitRibbon);
function go(n){n=Math.max(0,Math.min(pages.length-1,n));index=n;lockedUntil=Date.now()+750;main.scrollTo({top:pages[n].offsetTop,behavior:motion.matches?'instant':'smooth'});dots.forEach((d,i)=>i===n?d.setAttribute('aria-current','page'):d.removeAttribute('aria-current'));pages.forEach((p,i)=>{p.inert=i!==n});}
function withinContent(direction,target){const c=target.closest('.page-content');return c&&getComputedStyle(c).overflowY!=='hidden'&& (direction>0?c.scrollTop+c.clientHeight<c.scrollHeight-3:c.scrollTop>3)}
main.addEventListener('wheel',e=>{if(e.ctrlKey||Math.abs(e.deltaX)>Math.abs(e.deltaY))return;const direction=Math.sign(e.deltaY);if(withinContent(direction,e.target))return;e.preventDefault();if(Date.now()<lockedUntil)return;wheelSum+=e.deltaY;clearTimeout(wheelTimer);wheelTimer=setTimeout(()=>wheelSum=0,160);if(Math.abs(wheelSum)>24){go(index+Math.sign(wheelSum));wheelSum=0}},{passive:false});
main.addEventListener('touchstart',e=>{touchY=e.touches.length===1?e.touches[0].clientY:null},{passive:true});main.addEventListener('touchmove',e=>{if(touchY===null)return;const dy=touchY-e.touches[0].clientY;if(Math.abs(dy)>12&&!withinContent(Math.sign(dy),e.target))e.preventDefault()},{passive:false});main.addEventListener('touchend',e=>{if(touchY===null)return;const dy=touchY-e.changedTouches[0].clientY;touchY=null;if(Math.abs(dy)>45&&!withinContent(Math.sign(dy),e.target)&&Date.now()>lockedUntil)go(index+Math.sign(dy))},{passive:true});
dots.forEach((b,i)=>b.onclick=()=>go(i));document.querySelectorAll('a[href="#instructions"]').forEach(a=>a.onclick=e=>{e.preventDefault();go(1)});document.addEventListener('keydown',e=>{if(dialog.open||/INPUT|SELECT|TEXTAREA|BUTTON/.test(e.target.tagName))return;if(['PageDown','PageUp','ArrowDown','ArrowUp'].includes(e.key)){if(withinContent(['PageDown','ArrowDown'].includes(e.key)?1:-1,e.target))return;e.preventDefault();go(index+(['PageDown','ArrowDown'].includes(e.key)?1:-1))}});window.addEventListener('resize',()=>main.scrollTo({top:pages[index].offsetTop,behavior:'instant'}));go(location.hash==='#instructions'?1:0);
})();

